# Generated by Django 5.0.3 on 2024-04-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_student_img_alter_student_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/'),
        ),
    ]
